CREATE TRIGGER SCHEDULE_TRG 
BEFORE INSERT ON SCHEDULE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.CODE IS NULL THEN
      SELECT SCHEDULE_SEQ.NEXTVAL INTO :NEW.CODE FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
