CREATE TRIGGER TRAIN_COMPOSITION_TRG 
BEFORE INSERT ON TRAIN_COMPOSITION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT TRAIN_COMPOSITION_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
